#include <stdio.h>
#include <vector>
// Each new term in the Fibonacci sequence is generated by 
// adding the previous two terms. By starting with 1 and 2, 
// the first 10 terms will be:
// 
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose 
// values do not exceed four million, find the sum of the 
// even-valued terms.

std::vector<int> *getFibonacciList(int lim){
  auto vec = new std::vector<int>;
  for(int i = 1, j = 1; j < lim;) {
    int t = i + j;
    i = j;
    j = t;
    vec->push_back(t);
  }
  return vec;
}
int main(){
  auto vec = getFibonacciList(4000000);
  int sum = 0;
  for(int item : *vec)
    sum += (item%2==0)?item:0;
  printf("%d\n", sum);
}
