/**
 * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 * <p/>
 * 22=4, 23=8, 24=16, 25=32
 * 32=9, 33=27, 34=81, 35=243
 * 42=16, 43=64, 44=256, 45=1024
 * 52=25, 53=125, 54=625, 55=3125
 * <p/>
 * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
 * <p/>
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * <p/>
 * How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */
package problems20_29;

import java.math.BigInteger;
import java.util.ArrayList;

public class Problem29 {
    static ArrayList<BigInteger> l = new ArrayList<BigInteger>();

    public static void main(String args[]) {
        for (int a = 2; a <= 100; a++) {
            for (int b = 2; b <= 100; b++) {
                if (!l.contains(BigInteger.valueOf(a).pow(b))) {
                    l.add(BigInteger.valueOf(a).pow(b));
                }
            }
        }
        System.out.println(l.size());
    }
}
